import { readFileSync, statSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const moduleHtmlPath = resolve(process.cwd(), 'public/core-marker-priority/index.html')
const moduleDocument = readFileSync(moduleHtmlPath, 'utf8')
const moduleStylePath = resolve(process.cwd(), 'public/core-marker-priority/styles.css')
const moduleStyles = readFileSync(moduleStylePath, 'utf8')
const moduleHtml = `${moduleDocument}\n${moduleStyles}`
const moduleViewPath = resolve(process.cwd(), 'src/views/CoreMarkerPriorityView.vue')
const moduleView = readFileSync(moduleViewPath, 'utf8')
const sankeyView = readFileSync(resolve(process.cwd(), 'src/views/Icd11SankeyView.vue'), 'utf8')

describe('core marker priority production shell', () => {
  it('loads production data only from the backend API', () => {
    expect(moduleDocument).toContain('<link rel="stylesheet" href="styles.css">')
    expect(moduleHtml).toContain('/api/core-marker-priority/overview')
    expect(moduleHtml).toContain('/api/core-marker-priority/details/')
    expect(moduleHtml).toContain('cache:"no-store"')
    expect(moduleHtml).toContain('validateOverviewPayload')
    expect(moduleHtml).toContain('REQUIRED_SCORE_SCOPES')
    expect(moduleHtml).toContain('请重启后端以执行托管数据迁移')
    expect(moduleHtml).not.toContain('overview.js')
    expect(moduleHtml).not.toContain('details.js')
    expect(statSync(moduleHtmlPath).size).toBeLessThan(100 * 1024)
    expect(statSync(moduleStylePath).size).toBeGreaterThan(0)
  })

  it('contains launch-safe loading, timeout, failure, empty and no-result states', () => {
    expect(moduleHtml).toContain('REQUEST_TIMEOUT_MS=12000')
    expect(moduleHtml).toContain('class RequestTimeoutError')
    expect(moduleHtml).toContain('id="pageState"')
    expect(moduleHtml).toContain('后端接口响应成功，但当前数据集为空')
    expect(moduleHtml).toContain('详情接口响应超时')
    expect(moduleHtml).toContain('当前筛选下没有标记物')
  })

  it('supports four independent scoring levels and smart search suggestions', () => {
    expect(moduleHtml).toContain('id="fineFilter"')
    expect(moduleHtml).toContain('id="rankingScope"')
    expect(moduleHtml).toContain('目标物质细类内评价')
    expect(moduleHtml).toContain('id="searchSuggestions"')
    expect(moduleHtml).toContain('editDistance')
    expect(moduleHtml).toContain('function pinyinForms(value)')
    expect(moduleHtml).toContain('function valueMatchesQuery(value,query)')
    expect(moduleHtml).toContain('function searchTokens(value)')
    expect(moduleHtml).toContain('function buildSearchIndex()')
    expect(moduleHtml).toContain('if(value===token)return{score:160,type:"direct"}')
    expect(moduleHtml).toContain('function suggestionGroups()')
    expect(moduleHtml).toContain('return[{label:"分类路径"')
    expect(moduleHtml).toContain('{label:"生物标记物"')
    expect(moduleHtml).toContain('style="--suggestion-level:${entry.level}"')
    expect(moduleHtml).toContain('identityFields:[label]')
    expect(moduleHtml).toContain('identityFields:[label,english,drug,d.cas],pathFields:rowPath(d)')
    expect(moduleHtml).toContain('function searchFieldSetMatch(fieldSet,token)')
    expect(moduleHtml).toContain('if(entry.kind==="marker"&&(!identityHits||(tokens.length===1&&pathUsed)))return null')
    expect(moduleHtml).toContain('if(pathUsed)hints.push("路径关联")')
    expect(moduleHtml).toContain('suggestion-match-hint${hint==="路径关联"?" path":""}')
    expect(moduleHtml).toContain('if(!query){box.innerHTML="";closeSearchSuggestions();return}')
    expect(moduleHtml).not.toContain('可搜索四级分类或生物标记物')
    expect(moduleHtml).not.toContain('选中后再更新页面')
    expect(moduleHtml).toContain('<mark>${esc(text.slice(start,end))}</mark>')
    expect(moduleHtml).toContain('state.searchSelection={kind:"marker",id:entry.id,label:entry.label}')
    expect(moduleHtml).toContain('setFilterValues(entry.path)')
    expect(moduleHtml).not.toContain('function searchMatch(')
  })

  it('has explicit intermediate and mobile responsive breakpoints', () => {
    expect(moduleHtml).toContain('@media(max-width:900px)')
    expect(moduleHtml).toContain('@media(max-width:760px)')
    expect(moduleHtml).toContain('@media(max-width:680px)')
    expect(moduleHtml).toContain('.filter-guide-panel,.ranking-panel,.analytics,.compare-panel,.rules-panel{width:clamp(1180px,92%,1400px)}')
    expect(moduleHtml).toContain('.ranking-visual,.ranking-table-view{width:calc(100% - 24px)')
    expect(moduleHtml).toContain('@media(max-width:1180px){.filter-guide-panel,.ranking-panel,.analytics,.compare-panel,.rules-panel{width:100%}}')
    expect(moduleHtml).toContain('@media(max-width:1320px){col.col-subtype,col.col-fine,col.col-coverage{visibility:collapse}')
    expect(moduleHtml).toContain('@media(max-width:680px){col.col-score{visibility:collapse}.col-score{display:none}')
    expect(moduleHtml).toContain('.filter-guide-panel,.ranking-panel,.analytics,.compare-panel,.rules-panel{width:100%}.ranking-visual,.ranking-table-view{width:calc(100% - 16px)}')
    expect(moduleHtml).toContain('.shell{padding-top:77px}')
    expect(moduleHtml).toContain('.shell{padding:73px 9px 22px}')
  })

  it('relays iframe scroll position and reveals both headers when scrolling upward', () => {
    expect(moduleHtml).toContain('type:"core-marker-priority:scroll"')
    expect(moduleHtml).toContain('Math.min(1,scrollY/190)')
    expect(moduleHtml).toContain('scrollTop:scrollY')
    expect(moduleHtml).toContain('addEventListener("scroll",()=>notifyParent({type:"core-marker-priority:scroll"')
    expect(moduleHtml).toContain('{passive:true}')
    expect(moduleHtml).toContain('.shell{max-width:1600px;margin:auto;padding:85px')
    expect(moduleView).toContain("event.data.type === 'core-marker-priority:scroll'")
    expect(moduleView).toContain('function updateHeaderVisibility(scrollTop: number)')
    expect(moduleView).toContain('headerScrollTravel < 12')
    expect(moduleView).toContain("'--priority-header-opacity': drawerOpen.value || headerVisible.value ? '1' : '0'")
    expect(moduleView).toContain("'is-hidden': !(drawerOpen || headerVisible)")
    expect(moduleView).toContain("event.data.type === 'core-marker-priority:drawer'")
    expect(moduleView).toContain('drawerOpen.value = event.data.open === true')
    expect(moduleView).toContain('position: absolute;')
    expect(moduleView).toContain('opacity 0.45s ease')
    expect(moduleView).toContain('.prototype-shell {\n  position: relative;\n  height: 100%;')
    expect(moduleView).not.toContain('headerResizeObserver')
    expect(moduleView).not.toContain('--priority-header-row')
    expect(moduleView).not.toContain('--priority-header-offset')
    expect(moduleView).not.toContain('grid-template-rows')
    expect(sankeyView).toContain('const HEADER_SCROLL_THRESHOLD = 12')
    expect(sankeyView).toContain('headerVisible.value = direction < 0')
    expect(sankeyView).toContain("'--header-opacity': headerVisible.value ? '1' : '0'")
    expect(sankeyView).toContain("'is-hidden': !headerVisible")
    expect(sankeyView).not.toContain('--header-offset')
    expect(sankeyView).toContain('.sankey-map-header.site-header {\n    transition: none;')
  })

  it('does not render the score-evidence heatmap', () => {
    expect(moduleHtml).not.toContain('id="heatmapChart"')
    expect(moduleHtml).not.toContain('五项评分证据热图')
    expect(moduleHtml).not.toContain('renderHeatmap')
  })

  it('sizes the ranking viewport by result count and scrolls after the maximum height', () => {
    expect(moduleHtml).toContain('const RANKING_ROW_HEIGHT=34')
    expect(moduleHtml).toContain('const GROUP_ROW_HEIGHT=38')
    expect(moduleHtml).toContain('function configureBarRowHover(chart,seriesCount)')
    expect(moduleHtml).toContain('fontSize:12,fontWeight:700')
    expect(moduleHtml).toContain('shadowBlur:9')
    expect(moduleHtml).toContain('class="ranking-scroll"')
    expect(moduleHtml).toContain('id="rankingScrollFrame"')
    expect(moduleHtml).toContain('class="ranking-axis-head"')
    expect(moduleHtml).toContain('.ranking-axis-head{position:sticky;top:0')
    expect(moduleHtml).toContain('class="ranking-axis-y">生物标记物</div>')
    expect(moduleHtml).toContain('class="ranking-axis-rank">排名</div>')
    expect(moduleHtml).toContain('class="ranking-axis-title">得分构成</div>')
    expect(moduleHtml).toContain('class="ranking-axis-total">总分</div>')
    expect(moduleHtml).toContain('<span>0</span><span>20</span><span>40</span><span>60</span><span>80</span><span>100</span>')
    expect(moduleHtml).not.toContain('<aside class="panel selected">')
    expect(moduleHtml).not.toContain('id="selectedBody"')
    expect(moduleHtml).not.toContain('function renderSelected()')
    expect(moduleHtml).toContain('barMaxWidth:18')
    expect(moduleHtml).not.toContain('barMaxWidth:24')
    expect(moduleHtml).not.toContain('barMaxWidth:30')
    expect(moduleHtml).toContain('const RANKING_LAYOUT={desktop:{rank:54,marker:178,total:76},compact:{rank:36,marker:96,total:52}}')
    expect(moduleHtml).toContain('grid-template-columns:var(--ranking-rank-width,54px) var(--ranking-marker-width,178px) minmax(0,1fr) var(--ranking-total-width,76px)')
    expect(moduleHtml).toContain('grid:{left,right:layout.total')
    expect(moduleHtml).toContain('x:point[0]-layout.marker-10')
    expect(moduleHtml).toContain('x:point[0]-layout.marker+10')
    expect(moduleHtml).toContain('x:plotRight+layout.total/2')
    expect(moduleHtml).toContain('name:"摘要",type:"custom",silent:true')
    expect(moduleHtml).not.toContain('totalScore} · ${tierShort')
    expect(moduleHtml).not.toContain('function tierShort(')
    expect(moduleHtml).toContain('{key:"literatureScore",name:"文献证据",max:30,color:"#155F9D"}')
    expect(moduleHtml).toContain('{key:"spaceScore",name:"空间覆盖",max:30,color:"#3D7FB4"}')
    expect(moduleHtml).toContain('{key:"yearScore",name:"年份跨度",max:20,color:"#74A9CA"}')
    expect(moduleHtml).toContain('{key:"cfScore",name:"校准系数",max:10,color:"#16845B"}')
    expect(moduleHtml).toContain('{key:"gsScore",name:"管道衰减",max:10,color:"#59A482"}')
    expect(moduleDocument).toContain('<div class="break-summary" id="breakSummary" aria-label="分层参考线说明" hidden></div>')
    expect(moduleDocument).not.toContain('class="break-summary chart-only"')
    expect(moduleHtml).toContain('value:`${s.totalScore} / 100`')
    expect(moduleHtml).not.toContain('class="group-scroll"')
    expect(moduleHtml).toContain('.ranking-scroll{height:520px;overflow-x:hidden;overflow-y:scroll')
    expect(moduleHtml).toContain('const minHeight=compact?180:200,maxHeight=520')
    expect(moduleHtml).toContain('rows.length*RANKING_ROW_HEIGHT+24')
    expect(moduleHtml).toContain('$("rankingScrollFrame").style.height=`${visibleHeight}px`')
    expect(moduleHtml).toContain('$("rankingScroll").style.height=`${visibleHeight}px`')
    expect(moduleHtml).toContain('window.addEventListener("resize",()=>{closeRankingPickers();document.querySelectorAll(".legend-help")')
    expect(moduleHtml).toContain('.chart.groups{min-height:170px}')
    expect(moduleHtml).toContain('scrollbar-gutter:auto')
    expect(moduleHtml).toContain('class="persistent-scrollbar-thumb"')
    expect(moduleHtml).not.toContain('id="groupScrollbar"')
    expect(moduleHtml).toContain('id="rankingScrollbar"')
    expect(moduleHtml).toContain('function bindPersistentScrollbar(scrollId,barId)')
    expect(moduleHtml).toContain('scrollbar-width:none')
    expect(moduleHtml).toContain('dataZoom:[]')
    expect(moduleHtml).not.toContain('RANKING_DISPLAY_LIMIT')
    expect(moduleHtml).not.toContain('scoredRows.slice')
    expect(moduleHtml).not.toContain('const zoom=groups.length')
    expect(moduleHtml).toContain('class="ranking-meta"')
    expect(moduleHtml).toContain('class="chart-legend ranking-chart-legend chart-only" aria-label="排名图图例"><div class="ranking-meta" id="rankingNote"')
    expect(moduleHtml).not.toContain('各组独立分层，不绘制统一参考线')
    expect(moduleHtml).not.toContain('未生成分层参考线，仅提供排名')
    expect(moduleHtml).toContain('breakSummary.hidden=!thresholdVisible')
    expect(moduleHtml).toContain('<span class="threshold-prefix">分层参考线</span>')
    expect(moduleHtml).toContain('<i class="threshold-line low" aria-hidden="true"></i><b>低/中分界</b>')
    expect(moduleHtml).toContain('<i class="threshold-line high" aria-hidden="true"></i><b>中/高分界</b>')
    expect(moduleHtml).toContain('id:`threshold-hit-${index}`')
    expect(moduleHtml).toContain('symbolSize:[12,RANKING_ROW_HEIGHT]')
    expect(moduleHtml).toContain('setThresholdLineHover(Number(p.data?.thresholdIndex),true)')
    expect(moduleHtml).toContain('标记物优先级排名')
    expect(moduleHtml).toContain('id="inlineRules"')
    expect(moduleHtml).toContain('总览展示范围')
    expect(moduleHtml).not.toContain('id="ruleButton"')
    expect(moduleHtml).not.toContain('评分组 <strong>')
    expect(moduleHtml).not.toContain('class="compact-kpis"')
    expect(moduleHtml).not.toContain('各组独立断点')
    expect(moduleHtml).not.toContain('各组独立计算，可在图中上下滑动查看')
    expect(moduleHtml).not.toContain('<section class="kpis">')
    expect(moduleHtml).not.toContain('<header class="topbar">')
  })

  it('uses a compact five-lane score-density bubble plot with descriptive axes', () => {
    expect(moduleHtml).toContain('.chart.density{height:330px}')
    expect(moduleHtml).toContain('.chart.density{height:310px}')
    expect(moduleHtml).toContain('lanes=[-18,-9,0,9,18]')
    expect(moduleHtml).toContain('colors={0:"#74a9ca",10:"#3d7fb4",20:"#155f9d"}')
    expect(moduleHtml).toContain('symbolOffset:[lanes[laneIndex[x.evidence]++%5],0]')
    expect(moduleHtml).toContain('Math.max(10,Math.min(32,8+Math.sqrt(v[2])*4))')
    expect(moduleHtml).toContain('p.value[2]>=6?p.value[2]:""')
    expect(moduleHtml).toContain('name:"参数证据完整度（0–20）"')
    expect(moduleHtml).toContain('0:"未覆盖\\n0分",10:"部分覆盖\\n10分",20:"完整覆盖\\n20分"')
    expect(moduleHtml).toContain('name:"关注证据得分（0–80）"')
    expect(moduleHtml).toContain('state.scoreCell={attention:p.data.item.attention,evidence:p.data.item.evidence}')
  })

  it('integrates searchable filters into the four-step path and avoids repeated result totals', () => {
    expect(moduleHtml).toContain('class="search-icon"')
    expect(moduleHtml).toContain('class="search-control"')
    expect(moduleHtml).not.toContain('<div class="filter-row">')
    expect(moduleHtml).toContain('class="panel guide-panel filter-guide-panel filters"')
    expect(moduleHtml).toContain('class="filter-guide-toolbar"')
    expect(moduleHtml).toContain('class="reset-filter-button"')
    expect(moduleHtml).toContain('aria-label="清空全部筛选"')
    expect(moduleHtml).toContain('class="filter-state" hidden aria-hidden="true"')
    expect(moduleHtml).not.toContain('id="currentStepSelect"')
    expect(moduleHtml).toContain('<span id="rankingScopeLabel">排名层级</span><select id="rankingScope"')
    expect(moduleHtml).toContain('$("rankingScope").addEventListener("change",()=>setScope($("rankingScope").value))')
    expect(moduleHtml).toContain('if(scope==="targetType")return Boolean($("categoryFilter").value)')
    expect(moduleHtml).toContain('if(scope==="targetSubtype")return Boolean($("typeFilter").value)')
    expect(moduleHtml).toContain('if(scope==="targetFine")return Boolean($("subtypeFilter").value)')
    expect(moduleHtml).toContain('筛选结果共 <strong>${rows.length}</strong> 项')
    expect(moduleHtml).not.toContain('<span>参数证据完整 <strong>${completeCount}</strong></span>')
    expect(moduleHtml).not.toContain('const completeCount=')
    expect(moduleHtml).not.toContain('class="pending-selection"')
    expect(moduleHtml).not.toContain('id="pendingConfirm"')
    expect(moduleHtml).toContain('placeholder="搜索分类层级或标记物（支持中文、英文、拼音、ATC、CAS）"')
    expect(moduleHtml).toContain('class="suggestion-group" role="group"')
    expect(moduleHtml).toContain('data-suggestion-key=')
    expect(moduleHtml).toContain('if(state.searchSelection&&$("searchInput").value!==state.searchSelection.label)')
    expect(moduleHtml).not.toContain('renderSearchSuggestions();applyFilters()')
    expect(moduleHtml.match(/id="categoryFilter"/g)).toHaveLength(1)
    expect(moduleHtml.match(/id="typeFilter"/g)).toHaveLength(1)
    expect(moduleHtml.match(/id="subtypeFilter"/g)).toHaveLength(1)
    expect(moduleHtml.match(/id="fineFilter"/g)).toHaveLength(1)
    expect(moduleHtml).not.toContain('id="filterPath"')
    expect(moduleHtml).not.toContain('id="filterCount"')
    expect(moduleHtml).not.toContain('class="cascade-title"')
    expect(moduleHtml).not.toContain('全部目标物质类别')
    expect(moduleHtml).not.toContain('id="kpiTotal"')
    expect(moduleHtml).not.toContain('当前组 ${score(rows[0]).sampleSize} 项')
    expect(moduleHtml).not.toContain('加入比较')
    expect(moduleHtml).toContain('data-compare-id')
    expect(moduleHtml).toContain('data-ranking-view="table"')
    expect(moduleView).not.toContain('class="module-status"')
  })

  it('keeps the upper filter chart stable when only the ranking scope changes', () => {
    expect(moduleHtml).toContain('state.scope=scope;state.scoreCell=null;syncScopeButtons();applyFilters(false)')
    expect(moduleHtml).toContain('function applyFilters(updateGuide=true)')
    expect(moduleHtml).toContain('if(updateGuide)renderGroups()')
    expect(moduleHtml).toContain('if(updateGuide&&!$("guideChartShell").hidden)configureBarRowHover(groupChart,4)')
  })

  it('uses a direct four-step drill-down guide with concise click guidance', () => {
    const filtersIndex = moduleHtml.indexOf('class="panel guide-panel filter-guide-panel filters"')
    const guideIndex = moduleHtml.indexOf('id="groupChart"')
    const rankingIndex = moduleHtml.indexOf('id="rankingChart"')

    expect(filtersIndex).toBeGreaterThan(-1)
    expect(guideIndex).toBeGreaterThan(filtersIndex)
    expect(rankingIndex).toBeGreaterThan(guideIndex)
    expect(moduleHtml).toContain('id="guidePanelTitle">筛选路径')
    expect(moduleHtml).toContain('id="guideSteps"')
    expect(moduleHtml.match(/data-guide-step="[0-3]"/g)).toHaveLength(4)
    expect(moduleHtml).toContain('第 1 步：选择目标类别')
    expect(moduleHtml).not.toContain('筛选路径已完成')
    expect(moduleHtml).not.toContain('id="guideComplete"')
    expect(moduleHtml).toContain('class="guide-stage" id="guideStage"')
    expect(moduleHtml).toContain('.filter-guide-panel .guide-step.current::after,.guide-stage::before{display:none!important}')
    expect(moduleHtml).toContain('@media(prefers-reduced-motion:reduce)')
    expect(moduleHtml).toContain('function commitGroup(item)')
    expect(moduleHtml).not.toContain('function commitGroupByKey(key)')
    expect(moduleHtml).not.toContain('键盘选择')
    expect(moduleHtml).toContain('id="guideClickHint">单击条形查看并进入下一层')
    expect(moduleHtml).toContain('activeIndex===3?"单击条形查看标记物排名":"单击条形查看并进入下一层"')
    expect(moduleHtml).toContain('const chartHeight=Math.max(compact?150:170,groups.length*GROUP_ROW_HEIGHT+58)')
    expect(moduleHtml).not.toContain('class="guide-axis-name">生物标记物</div>')
    expect(moduleHtml).toContain('legend:{show:false,selectedMode:false}')
    expect(moduleHtml).toContain('grid:{left:tiny?105:compact?136:330,right:tiny?58:compact?112:154')
    expect(moduleHtml).toContain('barMaxWidth:16')
    expect(moduleHtml).toContain('position:group[key]>=3?"inside":"top"')
    expect(moduleHtml).toContain('graphic:[{type:"text",silent:true,left:"center",bottom:3,style:{text:"生物标记物数量"')
    expect(moduleHtml).toContain('xAxis:{type:"value",position:"bottom",min:0,minInterval:1,axisLabel:')
    expect(moduleHtml).toContain('yAxis:{type:"category",position:"left"')
    expect(moduleHtml).toContain('groupChart.clear();groupChart.setOption')
    expect(moduleHtml).toContain('clearBarRowHover(groupChart);')
    expect(moduleHtml).toContain('clearBarRowHover(rankingChart);')
    expect(moduleHtml).toContain('function transitionGuide(update)')
    expect(moduleHtml).not.toContain('id="guideViewRanking"')
    expect(moduleHtml).not.toContain('id="guideCompleteViewRanking"')
    expect(moduleHtml).not.toContain('function viewCurrentRanking()')
    expect(moduleHtml).toContain('function scrollToContextTarget(target)')
    expect(moduleHtml).toContain('target.scrollIntoView({behavior:reduced?"auto":"smooth",block:"start"})')
    expect(moduleHtml).toContain('.guide-step{scroll-margin-top:12px}')
    expect(moduleHtml).toContain('id="rankingPanel"')
    expect(moduleHtml).toContain('.shell{max-width:1544px')
    expect(moduleHtml).toContain('.filter-guide-panel .guide-step-number{width:26px;height:26px;font-size:13px}')
    expect(moduleHtml).toContain('.filter-guide-panel .guide-step-label{font-size:14px}')
    expect(moduleHtml).toContain('class="guide-prompt-note"')
    expect(moduleHtml).not.toContain('id="groupNote"')
    expect(moduleHtml).not.toContain('id="pendingSelection"')
    expect(moduleHtml).toContain('number.classList.toggle("completed-check",completed)')
    expect(moduleHtml).toContain('number.textContent=completed?"":String(index+1)')
    expect(moduleHtml).toContain('.guide-step-number.completed-check::after')
    expect(moduleHtml).toContain('clip-path:polygon(0 44%,15% 29%,40% 58%,85% 4%,100% 18%,42% 89%)')
    expect(moduleHtml).toContain('.filter-guide-panel .guide-step.upcoming{background:#F8FAFC;color:#94A3B8;opacity:1}')
    expect(moduleDocument).toContain('<ol class="guide-steps" id="guideSteps" aria-label="四级筛选路径">')
    expect(moduleDocument).toContain('<button class="guide-step" data-guide-step="0" type="button" disabled>')
    expect(moduleHtml).toContain('card.setAttribute("aria-disabled",String(!completed))')
    expect(moduleHtml).toContain('card.disabled=!completed')
    expect(moduleHtml).toContain('document.querySelectorAll("[data-guide-step]").forEach(card=>card.addEventListener("click",()=>editGuideStep(Number(card.dataset.guideStep))))')
    expect(moduleHtml).toContain('state.searchSelection=null;state.selectedId=null;$("searchInput").value="";closeSearchSuggestions();setFilterValues(values)')
    expect(moduleDocument).not.toContain('data-edit-step')
    expect(moduleDocument).not.toContain('guide-step-edit')
    expect(moduleHtml).toContain('formatter:`共 ${group.count} 个`')
    expect(moduleHtml).not.toContain('选择 →')
    expect(moduleHtml).toContain('hint:"点击进入下一层"')
    expect(moduleHtml).toContain('shadowStyle:{color:"rgba(37,99,235,.08)"}')
  })

  it('uses restrained active-state styling for the persistent chart scrollbars', () => {
    expect(moduleHtml).toContain('background:#c3ced8')
    expect(moduleHtml).toContain('.persistent-scrollbar.is-scrolling .persistent-scrollbar-thumb')
    expect(moduleHtml).toContain('.persistent-scrollbar.is-dragging .persistent-scrollbar-thumb')
    expect(moduleHtml).toContain('setTimeout(()=>bar.classList.remove("is-scrolling"),180)')
    expect(moduleHtml).toContain('bar.classList.add("is-dragging")')
    expect(moduleHtml).toContain('.persistent-scrollbar-thumb{transition:none}')
    expect(moduleHtml).toContain('.ranking-select-label{display:flex;align-items:center;gap:8px')
    expect(moduleHtml).toContain('.ranking-select-label select{min-width:156px;height:38px')
    expect(moduleHtml).toContain('function initRankingPickers()')
    expect(moduleHtml).toContain('class="ranking-select-option${index===selected?" selected":""}"')
    expect(moduleHtml).toContain('["ArrowDown","ArrowUp","Home","End","Enter"," ","Escape"]')
    expect(moduleHtml).toContain('.ranking-select-menu{position:absolute;z-index:40')
    expect(moduleHtml).toContain('.ranking-picker.align-end .ranking-select-menu{right:0;left:auto}')
    expect(moduleHtml).toContain('.chart-legend{display:flex;align-items:center;justify-content:flex-end;gap:12px;flex-wrap:wrap')
    expect(moduleHtml).toContain('font-size:12px;user-select:none;pointer-events:none')
    expect(moduleHtml).toContain('width:9px;height:9px;margin-right:5px')
    expect(moduleHtml).toContain('class="legend-tooltip" id="legendTipLiterature" role="tooltip"')
    expect(moduleHtml).toContain('.legend-help-wrap:hover .legend-tooltip,.legend-help-wrap:focus-within .legend-tooltip')
    expect(moduleHtml).toContain('.chart-legend .legend-tooltip{width:min(220px,calc(100vw - 32px))')
    expect(moduleHtml).toContain('width=Math.min(220,innerWidth-32)')
    expect(moduleHtml).toContain('overflow-wrap:anywhere;word-break:break-word')
    expect(moduleHtml).toContain('document.activeElement?.classList.contains("legend-help")')
  })

  it('backfills unique parent paths and asks before resolving ambiguous descendants', () => {
    expect(moduleHtml).toContain('const FILTER_FIELDS=["category","targetType","targetSubtype","targetFine"]')
    expect(moduleHtml).toContain('function matchingPaths(index,value)')
    expect(moduleHtml).toContain('path.slice(0,index+1).join("\\u0001")')
    expect(moduleHtml).toContain('function handleHierarchyChange(id)')
    expect(moduleHtml).toContain('function openPathDialog(pending)')
    expect(moduleHtml).toContain('id="pathDialogBackdrop"')
    expect(moduleHtml).toContain('选择所属路径')
    expect(moduleHtml).toContain('function choosePath(choice)')
    expect(moduleHtml).toContain('function editGuideStep(index)')
    expect(moduleHtml).toContain('pendingRankingJump:false')
    expect(moduleHtml).not.toContain('pendingGroup')
    expect(moduleHtml).toContain('commitFilterState(true,false)')
    expect(moduleHtml).toContain('const complete=filterValues().every(Boolean)')
    expect(moduleHtml).toContain('state.pendingRankingJump=true;if(entry.kind==="scope")')
    expect(moduleHtml).toContain('state.selectedId=entry.id;setFilterValues(entry.path)')
  })

  it('embeds the ranking details table as a persistent alternate ranking view', () => {
    expect(moduleHtml).toContain('data-ranking-view="chart"')
    expect(moduleHtml).toContain('data-ranking-view="table"')
    expect(moduleHtml).toContain('>排名图</button>')
    expect(moduleHtml).toContain('>明细表</button>')
    expect(moduleHtml).toContain('id="rankingChartView" role="tabpanel"')
    expect(moduleHtml).toContain('id="rankingTableView" role="tabpanel"')
    expect(moduleHtml).toContain('rankingView:"chart"')
    expect(moduleHtml).toContain('function setRankingView(view)')
    expect(moduleHtml).toContain('function syncRankingView()')
    expect(moduleHtml).toContain('document.querySelectorAll(".chart-only").forEach(e=>e.style.visibility=c?"":"hidden")')
    expect(moduleHtml).toContain('id="resultCols"')
    expect(moduleHtml).toContain('id="resultHead"')
    expect(moduleHtml).toContain('const TABLE_COLUMNS=')
    expect(moduleHtml).toContain('{key:"category",label:"目标类别",cls:"col-category"}')
    expect(moduleHtml).toContain('{key:"targetSubtype",label:"目标物质子类",cls:"col-subtype",sort:true}')
    expect(moduleHtml).toContain('{key:"targetFine",label:"目标物质细类",cls:"col-fine",sort:true}')
    expect(moduleHtml).toContain('{key:"marker",label:"生物标记物",width:170,cls:"col-marker",sort:true}')
    expect(moduleHtml).toContain('{key:"result",label:"排名/样本",width:88,cls:"col-result",sort:true,num:true}')
    expect(moduleHtml).toContain('{key:"total",label:"总分",width:64,cls:"col-total",sort:true,num:true}')
    expect(moduleHtml).not.toContain('{key:"category",label:"目标类别",cls:"col-category",sort:true}')
    expect(moduleHtml).toContain('{key:"tier",label:"组内分层",width:84,cls:"col-tier"}')
    expect(moduleHtml).not.toContain('{key:"tier",label:"组内分层",width:84,cls:"col-tier",sort:true}')
    expect(moduleHtml).toContain('function tierDisplay(s)')
    expect(moduleHtml).toContain('title="当前组未生成分层">—</span>')
    expect(moduleHtml).toContain('["未分层","none","#E2E8F0"]')
    expect(moduleHtml).not.toContain('{key:"coverage",label:"国家/点位",width:84,cls:"col-coverage",sort:true')
    expect(moduleHtml).toContain('{key:"literatureScore",label:"文献分",title:"文献评分（30分）",width:52,cls:"col-score col-literature",num:true}')
    expect(moduleHtml).toContain('{key:"spaceScore",label:"空间分",title:"空间评分（30分）",width:52,cls:"col-score col-space",num:true}')
    expect(moduleHtml).toContain('{key:"yearScore",label:"年份分",title:"年份评分（20分）",width:52,cls:"col-score col-year",num:true}')
    expect(moduleHtml).toContain('{key:"cfScore",label:"校准分",title:"校准系数评分（10分）",width:58,cls:"col-score col-cf",num:true}')
    expect(moduleHtml).toContain('{key:"gsScore",label:"衰减分",title:"管道衰减评分（10分）",width:66,cls:"col-score col-gs",num:true}')
    expect(moduleHtml).toContain('const component=COMPONENTS.find(item=>item.key===c.key)')
    expect(moduleHtml).toContain('tableSortState:{key:"result",direction:"asc"}')
    expect(moduleHtml).toContain('function sortTableRows(rows)')
    expect(moduleHtml).toContain('if(key==="marker")return[d.name||d.drug||d.biomarker,d.biomarker||""]')
    expect(moduleHtml).toContain('const primary=d.name||d.drug||d.biomarker||"未命名标记物",secondary=d.biomarker&&d.biomarker!==primary?d.biomarker:""')
    expect(moduleHtml).toContain('function setSortState(key,direction)')
    expect(moduleHtml).toContain('state.tableSortState={key,direction};renderTable()')
    expect(moduleHtml).toContain('return state.filtered.slice().sort(sortRows)')
    expect(moduleHtml).toContain('data-sort-key="${column.key}"')
    expect(moduleHtml).toContain('aria-sort="${active?')
    expect(moduleHtml).toContain('disabled=c.sort&&values.size<2')
    expect(moduleHtml).toContain('toggle.hidden=state.filtered.length<=50')
    expect(moduleHtml).toContain('收起至前 50 项')
    expect(moduleHtml).toContain('展开全部（${state.filtered.length}）')
    expect(moduleHtml).toContain('table-layout:fixed')
    expect(moduleHtml).toContain('overflow-x:hidden')
    expect(moduleHtml).toContain('text-overflow:ellipsis;white-space:nowrap')
    expect(moduleHtml).not.toContain('element.hidden=!chartActive')
    expect(moduleHtml).toContain('state.rankingView!=="table"')
    expect(moduleHtml).toContain('.ranking-table-view .table-wrap{max-height:600px')
    expect(moduleHtml).toContain('.ranking-table-view .table-wrap{max-height:520px}')
    expect(moduleHtml).not.toContain('<th>样本提示</th>')
    expect(moduleHtml).not.toContain('<th>证据短板</th>')
    expect(moduleHtml).toContain('colspan="${TABLE_COLUMNS.length}"')
    expect(moduleHtml).not.toContain('min-width:1480px')
    expect(moduleHtml).not.toContain('<th class="num">文献</th>')
    expect(moduleHtml).not.toContain('<th class="num">空间</th>')
    expect(moduleHtml).not.toContain('<th class="num">年份</th>')
    expect(moduleHtml).not.toContain('id="tablePanel"')
    expect(moduleHtml).not.toContain('id="tableCollapseButton"')
    expect(moduleHtml).not.toContain('tableExpanded')
    expect(moduleHtml).toContain('完整结果可通过上方“明细表”视图查看')
    expect(moduleHtml).not.toContain('完整结果可在上方“评分排名明细”中展开查看')
  })

  it('keeps calculation rules collapsed until the full-width disclosure is opened', () => {
    expect(moduleHtml).toContain('class="rules-toggle" id="rulesToggle"')
    expect(moduleHtml).toContain('aria-expanded="false" aria-controls="inlineRules"')
    expect(moduleHtml).toContain('class="rules-body" id="inlineRules" hidden')
    expect(moduleHtml).toContain('$("rulesToggle").setAttribute("aria-expanded",String(!expanded))')
    expect(moduleHtml).toContain('$("inlineRules").hidden=expanded')
    expect(moduleHtml).toContain('.rules-body[hidden]{display:none}')
  })

  it('places ranking controls in a dedicated toolbar and exposes a structured drawer', () => {
    const headingStart = moduleDocument.indexOf('<div class="ranking-heading">')
    const switchIndex = moduleDocument.indexOf('class="ranking-view-switch"')
    const toolbarIndex = moduleDocument.indexOf('<div class="ranking-toolbar">')
    const scopeIndex = moduleDocument.indexOf('<span id="rankingScopeLabel">排名层级</span>')
    expect(switchIndex).toBeGreaterThan(headingStart)
    expect(switchIndex).toBeLessThan(toolbarIndex)
    expect(scopeIndex).toBeGreaterThan(toolbarIndex)
    expect(moduleHtml).toContain('.ranking-head{min-height:78px;padding:14px 20px;align-items:center;justify-content:space-between')
    expect(moduleHtml).toContain('.ranking-toolbar{position:relative;z-index:18;display:flex;align-items:center;justify-content:space-between')
    expect(moduleHtml).toContain('@media(min-width:901px){.filter-guide-toolbar{padding-inline:24px}')
    expect(moduleHtml).toContain('.ranking-visual,.ranking-table-view{width:calc(100% - 48px)')
    expect(moduleHtml).toContain('.ranking-select-label select{min-width:156px;height:38px')
    expect(moduleDocument).toContain('id="rankingScope"')
    expect(moduleDocument).not.toContain('id="rankingSort"')
    expect(moduleHtml).toContain('function syncRankingPickers(){syncRankingPicker("rankingScope")}')
    expect(moduleHtml).toContain('["rankingScope"].forEach(id=>')
    expect(moduleHtml).toContain('id="drawerIdentity"')
    expect(moduleHtml).toContain('id="drawerPath"')
    expect(moduleHtml).toContain('role="tablist" aria-label="标记物详情"')
    expect(moduleHtml).toContain('grid-template-columns:repeat(4,minmax(0,1fr))')
    expect(moduleHtml).toContain('grid-template-columns:repeat(2,minmax(0,1fr))')
    expect(moduleHtml).toContain('.drawer{top:72px;width:min(820px,64vw);height:calc(100dvh - 72px)')
    expect(moduleHtml).toContain('.drawer{top:64px;width:100vw;height:calc(100dvh - 64px)')
    expect(moduleHtml).toContain('notifyParent({type:"core-marker-priority:drawer",open:true})')
    expect(moduleHtml).toContain('notifyParent({type:"core-marker-priority:drawer",open:false})')
    expect(moduleHtml.match(/id:"(overview|category|targetType|targetSubtype|targetFine|coverage|aux|source)"/g)).toHaveLength(8)
    expect(moduleHtml).toContain('section("四级排名概览"')
    expect(moduleHtml).toContain('section("评分构成"')
    expect(moduleHtml).toContain('section("点位说明"')
    expect(moduleHtml).toContain('section("参数说明"')
    expect(moduleHtml).toContain('section("来源清单"')
  })
})
